# Generated by Django 5.1.7 on 2025-03-20 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ref', models.CharField(max_length=250, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
